In [9]:
import numpy as np

In [10]:
a = np.array([(4,3,12,34),(23,5,11,56)])

In [11]:
a

array([[ 4,  3, 12, 34],
       [23,  5, 11, 56]])

In [12]:
a.shape  # shape is used to know how mny rows and columns

(2, 4)

In [13]:
a.size  #total number of elements

8

In [14]:
a[0]

array([ 4,  3, 12, 34])

In [15]:
a.flatten()

array([ 4,  3, 12, 34, 23,  5, 11, 56])

In [24]:
b =np.array([(4,6,8,12,2),(1,3,5,7,9),(3,6,9,12,15)]) # 3 dimentional array

In [25]:
b

array([[ 4,  6,  8, 12,  2],
       [ 1,  3,  5,  7,  9],
       [ 3,  6,  9, 12, 15]])

In [26]:
c =b.reshape(5,3)  #converting it to 3 dimentional aray

In [27]:
c

array([[ 4,  6,  8],
       [12,  2,  1],
       [ 3,  5,  7],
       [ 9,  3,  6],
       [ 9, 12, 15]])

In [29]:
d = c.reshape(2,2,3)

ValueError: cannot reshape array of size 15 into shape (2,2,3)

In [30]:
e =np.array([(3,2,1,5,7,4),(9,8,5,3,2,1)])

In [31]:
e

array([[3, 2, 1, 5, 7, 4],
       [9, 8, 5, 3, 2, 1]])

In [33]:
e.reshape(3,4)  # 3 rows and 4 columns - 3 dimentional array

array([[3, 2, 1, 5],
       [7, 4, 9, 8],
       [5, 3, 2, 1]])

In [36]:
f =e.reshape(6,2)  # 6 dimentional array

In [37]:
f

array([[3, 2],
       [1, 5],
       [7, 4],
       [9, 8],
       [5, 3],
       [2, 1]])

In [40]:
g =f.reshape(2,2,3)  # 2 dimentional arrays having 3 elements in each

In [41]:
g

array([[[3, 2, 1],
        [5, 7, 4]],

       [[9, 8, 5],
        [3, 2, 1]]])

# metrics operations

In [46]:
h =np.array([(3,5,6,7),(1,3,7,9)])

In [47]:
h

array([[3, 5, 6, 7],
       [1, 3, 7, 9]])

In [49]:
m = np.matrix(h)

In [50]:
m

matrix([[3, 5, 6, 7],
        [1, 3, 7, 9]])

In [53]:
n =np.matrix('2,4,6,1;8,4,2,1') # defining values in matrix function

In [54]:
n

matrix([[2, 4, 6, 1],
        [8, 4, 2, 1]])

In [55]:
o =np.matrix('24,12 ;8,4;10,5;9,3')

In [56]:
o

matrix([[24, 12],
        [ 8,  4],
        [10,  5],
        [ 9,  3]])

In [59]:
i=np.diagonal(m)

In [60]:
i

array([3, 3])

In [62]:
j =np.diagonal(o)

In [63]:
j

array([24,  4])

In [66]:
k=np.min(o)

In [67]:
k

3

In [68]:
p =np.max(o)

In [69]:
p

24

In [71]:
x =np.matrix('4,1,5;2,5,1;6,7,2')
y =np.matrix('2,4,5;9,12,2;5,2,6')

In [72]:
x

matrix([[4, 1, 5],
        [2, 5, 1],
        [6, 7, 2]])

In [73]:
y

matrix([[ 2,  4,  5],
        [ 9, 12,  2],
        [ 5,  2,  6]])

In [74]:
z =x * y

In [75]:
z

matrix([[ 42,  38,  52],
        [ 54,  70,  26],
        [ 85, 112,  56]])