In [1]:
from numpy import *

In [2]:
arr = array([2,21,34,12,25])
ar =array([10,3,45,6,11])
a =arr +ar
print(a)

[12 24 79 18 36]


In [3]:
c =arr * ar
print(c)

[  20   63 1530   72  275]


In [4]:
aa = array([2,21,34,12,25])

In [5]:
print(cos(aa))

[-0.41614684 -0.54772926 -0.84857027  0.84385396  0.99120281]


In [6]:
print(sin(aa))

[ 0.90929743  0.83665564  0.52908269 -0.53657292 -0.13235175]


In [7]:
print(tan(aa))

[-2.18503986 -1.52749853 -0.62349896 -0.63585993 -0.13352641]


In [8]:
print(sqrt(aa))

[1.41421356 4.58257569 5.83095189 3.46410162 5.        ]


In [9]:
print(max(aa))

34


In [10]:
print(min(aa))

2


In [11]:
id(aa)

2016068471744

In [13]:
ab =aa.view()

In [14]:
ab

array([ 2, 21, 34, 12, 25])