In [1]:
import numpy as np
a =np.array([(20,3,21,45,67) ,(5,51,23,31) ,(11,2,90,5,7)])
print(a)

[(20, 3, 21, 45, 67) (5, 51, 23, 31) (11, 2, 90, 5, 7)]


In [2]:
a =np.array([(5,6,73,2),(4,7,9,2,12),(8,3,4,5,1)])

In [3]:
a

array([(5, 6, 73, 2), (4, 7, 9, 2, 12), (8, 3, 4, 5, 1)], dtype=object)

In [4]:
print(a.dtype)

object


In [6]:
b=np.array([8,9,7,5])

In [7]:
b

array([8, 9, 7, 5])

In [8]:
b.dtype

dtype('int32')

In [10]:
import  numpy as np
a =np.array([(20,3,21,45,67)])
print(a)


[[20  3 21 45 67]]


In [11]:
b =np.array([(20,3,21,45,67),(3,5,6,7,8),(11,2,4,9,10),(21,23,45,67)])
print(b)


[(20, 3, 21, 45, 67) (3, 5, 6, 7, 8) (11, 2, 4, 9, 10) (21, 23, 45, 67)]


In [12]:
c =np.array([(4.2,4.5,6.7,2.1)] ,int)
print(c)


[[4 4 6 2]]


In [13]:
d =np.array([(20,3,21,45,67)] ,float)
print(d)


[[20.  3. 21. 45. 67.]]


In [14]:
e =np.linspace(0,10,5)  #start stop ,part - how many places to divide 10
print("partisioning :" ,e)


partisioning : [ 0.   2.5  5.   7.5 10. ]


In [15]:
f = np.logspace(1,20,5)     # log 0f 1 to 20 and partition it into 5
print('log space :' ,f)
print('%.2f' %f[1])


log space : [1.00000000e+01 5.62341325e+05 3.16227766e+10 1.77827941e+15
 1.00000000e+20]
562341.33


In [16]:
g = np.zeros(5)
print("zeros :" ,g)

zeros : [0. 0. 0. 0. 0.]


In [17]:
h =np.ones(5)
print("ones :" ,h)


ones : [1. 1. 1. 1. 1.]


In [18]:
i = np.ones(5,int)
print('only integer values:' ,i)


only integer values: [1 1 1 1 1]


In [19]:
j =np.arange(1,10 ,2)  # print 1 ,excape 2 places and print next up till 10
print('arange values :' ,j)

arange values : [1 3 5 7 9]
